# Dependencies
markdown:         kramdown
#highlighter:      pygments

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
# Permalinks
permalink: /_posts/:year/:month/:day/:title.html
#relative_permalinks: true
gems: [jekyll-paginate]

# Setup
title:            Swim Performance Analytics
tagline:          'Empowering swimming data scientists'
description:      'A data science blog dedicated to informing those with a vested interest in all things swimming related'
url:              http://localhost:4000
baseurl:          /
excerpt_separator: <!--more-->

paginate:         3

author:
  name:           'Chris Brammer'

linkedin: chrisbrammer
twitter: brammerc
instagram: clbsandwch

github:
  repo:           https://github.com/brammerc
  hyde:           https://github.com/poole/hyde
