# Dependencies
markdown:         kramdown
highlighter:      rouge #pygments

# Permalinks
permalink: /_posts/:year/:month/:day/:title.html
#relative_permalinks: true
plugins: [jekyll-paginate]

# Setup
title:            Swim Performance Analytics
tagline:          'Empowering swimming data scientists'
description:      'Sharing data science tools and methods with the competitive swimming community'
url:              https://brammerc.github.io
baseurl:          https://brammerc.github.io/
excerpt_separator: <!--more-->

paginate:         3

author:
  name:           'Chris Brammer'

linkedin: chrisbrammer
twitter: brammerc
instagram: humanperformancephd

github:
  repo:           https://github.com/brammerc
  hyde:           https://github.com/poole/hyde
